version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev"]

volumes:
  frontend_node_modules:
